### ISSUE TITLE
Exception on the  non-root environment.

### ISSUE THREAD

**Issue by monaka** [eclipse/che-theia#281]
### Description

It looks the-theia can't access `/proc/net/tcp6` in the instance running as non-root.

### Reproduction Steps

1. Run as the non-root instance
2. Start workspace
3. Check logs from `che-theia` container.

**OS and version:**    

7.0.0-RC-2.0-SNAPSHOT

**Diagnostics:** 

```
root ERROR [hosted-plugin: 54] (node:54) UnhandledPromiseRejectionWarning: Error: Unable to execut
e the command cat /proc/net/tcp6: Error: Command failed: cat /proc/net/tcp6
cat: can't open '/proc/net/tcp6': No such file or directory

    at new CliError (/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/cli-error.js:32:28)
    at /tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/command.js:69:40
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
```

**Comment by monaka** [comment]
I misunderstood about this issue. Indeed there have some issues related on root/non-root environment.
But this `/proc/net/tcp6` issue is an individual.  

In some environments (at least Azure AKS), IPv6 is disable and `/proc/net/tcp6` isn't created.

```
$ kubectl exec -it --namespace=banco workspacewvws39a5loq3c0oa.shell-5556494f8c-tkkdg ls /proc/net
Defaulting container name to shell.
Use 'kubectl describe pod/workspacewvws39a5loq3c0oa.shell-5556494f8c-tkkdg -n banco' to see all of the containers in this pod.
arp                 ip6_tables_names    netfilter  route         tcp
dev                 ip6_tables_targets  netlink    rpc           udp
dev_mcast           ip_mr_cache         netstat    rt_acct       udplite
fib_trie            ip_mr_vif           packet     rt_cache      unix
fib_triestat        ip_tables_matches   protocols  snmp          wireless
icmp                ip_tables_names     psched     sockstat      xfrm_stat
igmp                ip_tables_targets   ptype      softnet_stat
ip6_tables_matches  mcfilter            raw        stat
```
