### ISSUE TITLE
Can't build Theia on Alpine Linux

### ISSUE THREAD

**Issue by monaka** [eclipse/che-theia#306]
### Description

The master branch after merged https://github.com/theia-ide/theia/pull/5055 won't be built on Alpine Linux.
Because Replaced Ffmpeg depends on Glibc. (see also: logs below)
It isn't caused by che-theia. But it should be managed to fix by Che side, IMO.
 
### Reproduction Steps

```
git clone https://github.com/theia-ide/theia.git
cd theia
yarn || npx electron-replace-ffmpeg && npx electron-codecs-test && yarn
```

**OS and version:**    

**Diagnostics:** 

```
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Downloading tmp-1744-0-ffmpeg-v3.1.7-linux-x64.zip
[============================================>] 100.0% of 1.11 MB (1.11 MB/s)
Downloaded ffmpeg shared library { version: "v3.1.7", dist: "/projects/theia/node_modules/electron/dist" }.
Successfully replaced "/projects/theia/node_modules/electron/dist/libffmpeg.so".
Error: Error relocating /projects/theia/node_modules/electron/dist/libffmpeg.so: __isnan: symbol not found
    at exports.libffmpegCodecs (/projects/theia/dev-packages/electron/electron-ffmpeg-lib.js:88:19)
    at main (/projects/theia/dev-packages/electron/electron-codecs-test.js:56:20)
    at Object.<anonymous> (/projects/theia/dev-packages/electron/electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by monaka** [comment]
I close this as fixed via theia-ide/theia#5587
